#ifndef ESTRUCTURAS_UTILS_H
#define ESTRUCTURAS_UTILS_H

typedef enum {
    // HANDSHAKES
    HANDSHAKE_STORAGE,
    HANDSHAKE_WORKER,
    HANDSHAKE_QUERY_CONTROL,
    HANDSHAKE_MASTER,
    HANDSHAKE_OK,
    HANDSHAKE_ERROR,

    // HEADERS QUE RECIBE STORAGE
    CREATE_FILE,
    TRUNCATE_FILE,
    TAG_FILE,
    COMMIT_TAG,
    WRITE_BLOCK,
    READ_BLOCK,
    REMOVE_TAG,

    // HEADERS QUE RECIBE WORKER
    RESPUESTA_CREATE_FILE,

} t_header;

typedef enum{
    INSTRUCCION_CREATE,
    INSTRUCCION_TRUNCATE,
    INSTRUCCION_WRITE,
    INSTRUCCION_READ,
    INSTRUCCION_TAG,
    INSTRUCCION_COMMIT,
    INSTRUCCION_FLUSH,
    INSTRUCCION_DELETE,
    INSTRUCCION_END,
} t_tipo_instruccion;

#endif